In [ ]:
import numpy as np

In [ ]:
x1=np.array([3,1,2,4,3])
x2=np.array([6,3,4,7,5])
y=np.array([1,0,0,1,1])

In [ ]:
X=np.column_stack((np.ones(5),x1,x2))

In [ ]:
B=np.linalg.inv(X.T@X)@X.T@y

In [ ]:
b0,b1,b2=B

In [ ]:
print("the constant value of (b0) is:",b0)
print("the constant value of (b1) is:",b1)
print("the constant value of (b2) is:",b2)

the constant value of (b0) is: -0.5999999999999837
the constant value of (b1) is: 0.3333333333333277
the constant value of (b2) is: 0.06666666666666865


In [ ]:
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [ ]:
z = X @ B
print("\nLinear combination (z):")
print(z)


Linear combination (z):
[ 0.8        -0.06666667  0.33333333  1.2         0.73333333]


In [ ]:
y_prob = np.array([sigmoid(val) for val in z])
print("\nPredicted Probabilities (Sigmoid_value):")
print(y_prob)


Predicted Probabilities (Sigmoid_value):
[0.68997448 0.4833395  0.58257021 0.76852478 0.67553632]


In [ ]:
y_pred = (y_prob > 0.5).astype(int)
print("\nPredicted Class Labels:")
print(y_pred)


Predicted Class Labels:
[1 0 1 1 1]


In [ ]:
TP = np.sum((y_pred == 1) & (y == 1))
TN = np.sum((y_pred == 0) & (y == 0))
FP = np.sum((y_pred == 1) & (y == 0))
FN = np.sum((y_pred == 0) & (y == 1))

In [ ]:
print("\nConfusion Matrix:")
print(f"TP = {TP}, FP = {FP}")
print(f"FN = {FN}, TN = {TN}")


Confusion Matrix:
TP = 3, FP = 1
FN = 0, TN = 1


In [ ]:
# Accuracy
Accuracy = (TP + TN) / (TP + TN + FP + FN)
# Precision
Precision = TP / (TP + FP)
# Recall (Sensitivity)
Recall = TP / (TP + FN)
# F1_Score
F1_Score = 2 * (Precision * Recall) / (Precision + Recall)


In [ ]:
print("\nPerformance Metrics:")
print(f"Accuracy = {Accuracy}")
print(f"Precision = {Precision}")
print(f"Recall (Sensitivity) = {Recall}")
print(f"F1_Score = {F1_Score}")


Performance Metrics:
Accuracy = 0.8
Precision = 0.75
Recall (Sensitivity) = 1.0
F1_Score = 0.8571428571428571
